version: "1.0"
info:
  model: int-scaffold
packages:
- name: ExternalGitTestProject
  gitServerName: https://github.com/
  gitUrl: https://github.com/y509522/ExternalGitTestProject
  gitUsername: y509522
  gitBranch: main
